flutter_application_path = '/Users/zhangsangong/Desktop/flutter_learn/iOSMixFlutter_project/pg_flutter'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'iOSProject' do
  install_all_flutter_pods(flutter_application_path)
end